name: Test Springboot Docker
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Podman
      run: |
        podman --version
        mvn -version
        java -version
    - name: Repo
      uses: actions/checkout@v4
    - name: S2I
      id: build_image
      uses: redhat-actions/s2i-build@v2
      with:
        path_context: '.'
        builder_image: 'registry.access.redhat.com/ubi9/openjdk-17'
        image: 'demo'
        tags: 'v3'
    - name: Quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: quay.io/edisson_pena
        username: edisson_pena
        password: Credibanco2024
    - name: Client
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: '4.6'
    - name: Login
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
        openshift_token: sha256~v-SNGBAQuBeZ4vFkElfewEytQYxkEoEyC0USf5zOrw0
        insecure_skip_tls_verify: true
        namespace: edisson-pena-dev
    - name: Deploy
      uses: redhat-actions/oc-new-app@v1
      with:
        app_name: demo
        image: quay.io/edisson_pena/demo:v1
        namespace: edisson-pena-dev
        registry_hostname: quay.io
        registry_username: edisson_pena
        registry_password: Credibanco2024